name: test

on:
  push:
    branches:
      - main

jobs:

  test2:

    runs-on: ubuntu-latest

    name: test3

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run dev (Run ESLint)

    - run: npm run test (Run Jest)